### ISSUE TITLE
Как дальше быть?

### ISSUE THREAD

**Issue by obamium235** [PyMxINI/ADLMARKETBOTLITE#3]
1) Хорошо бы добавить поддержку вебсокетов, но я не знаю какую библиотеку лучше выбрать
2) Текущий подход к организации внутренних циклов не очень правильный, хорошо бы их в потоки-треды засунуть, или асинхронность использовать. Опять же, вопрос: что лучше было бы?
3) Я добавил поддержку маркета tf2[.]tm, скорей чисто «а почему нет, смари прикол». Но я уже не уверен, стоит ли оно того, или лучше выбросить нафиг

**Comment by kasavaros** [comment]
Привет! Скрипт на "тм" выдает вот такую шляпу, если валюта в баксах:
tm check site inv request error: Trading only in rubles allowed

Как это пофиксить?
